import { useEffect, useMemo, useRef, useState } from "react";
import { HashRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import { AlertTriangle, ArrowRight, Clock3, ExternalLink, Menu, Search, X } from "lucide-react";
import { loadKnowledge, moduleMeta, searchItems, typeMeta } from "./knowledge";
import { publicEvidenceHref } from "./evidence";
import type { ContentType, KnowledgeIndex, KnowledgeItem } from "./types";

type Data = { index: KnowledgeIndex | null; state: "loading" | "ready" | "error" };
const moduleIds = Object.keys(moduleMeta) as KnowledgeItem["module"][];
const typeOptions: Array<ContentType | "all"> = ["all", "guide", "decision-card", "note", "case-study"];

function App() { const [data, setData] = useState<Data>({ index: null, state: "loading" }); const [attempt, setAttempt] = useState(0); useEffect(() => { loadKnowledge().then((index) => setData({ index, state: "ready" })).catch(() => setData({ index: null, state: "error" })); }, [attempt]); return <HashRouter><Shell data={data} retry={() => { setData({ index: null, state: "loading" }); setAttempt((value) => value + 1); }} /></HashRouter>; }

function Shell({ data, retry }: { data: Data; retry: () => void }) { const [open, setOpen] = useState(false); return <div className="app"><a className="skip" href="#main">跳到主要内容</a><header className="site-header"><Link className="brand" to="/"><strong>AI 工程知识库</strong><small>工程化思维 · 可验证 · 可复用 · 可迁移</small></Link><nav className={open ? "site-nav is-open" : "site-nav"} aria-label="主导航"><Link to="/library">探索知识</Link><Link to="/cases/p007-seven-role-case">实践案例</Link><Link to="/learn">方法论</Link><Link to="/library">资源库</Link><Link to="/">关于</Link><Link className="nav-search" aria-label="搜索知识库" to="/search"><Search />搜索</Link></nav><Link className="header-search" aria-label="打开搜索" to="/search"><Search />搜索知识、案例、方法…</Link><button className="menu" aria-label={open ? "关闭菜单" : "打开菜单"} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></header><main id="main" tabIndex={-1}>{data.state === "loading" ? <Loading /> : data.state === "error" ? <IndexError retry={retry} /> : <Pages items={data.index!.items} />}</main></div>; }

function Loading() { return <section className="state"><p className="eyebrow">INDEX / LOADING</p><h1>正在读取经校验索引</h1><div className="loading-route" aria-busy="true"><i /><i /><i /><i /></div></section>; }
function IndexError({ retry }: { retry: () => void }) { return <section className="state"><AlertTriangle /><p className="eyebrow">INDEX / UNAVAILABLE</p><h1>暂时无法读取这份资料</h1><p>索引没有通过校验，因此不会展示部分内容。</p><div className="actions"><button onClick={retry}>重新加载</button><Link to="/">返回首页</Link><Link to="/search">搜索</Link></div></section>; }
function Pages({ items }: { items: KnowledgeItem[] }) { return <Routes><Route path="/" element={<Home items={items} />} /><Route path="/library" element={<Library items={items} />} /><Route path="/learn" element={<Learn items={items} />} /><Route path="/search" element={<SearchPage items={items} />} /><Route path="/notes/:slug" element={<Detail items={items} />} /><Route path="/guides/:slug" element={<Detail items={items} />} /><Route path="/decisions/:slug" element={<Detail items={items} />} /><Route path="/cases/:slug" element={<Detail items={items} />} /><Route path="*" element={<NotFound />} /></Routes>; }

export function Home({ items }: { items: KnowledgeItem[] }) { const caseStudy = items.find((item) => item.contentType === "case-study"); const decision = items.find((item) => item.contentType === "decision-card"); const guide = items.find((item) => item.contentType === "guide"); const stages = [{ number: "01", title: "提出问题", text: "从工程问题而不是模型名开始。", to: "/library" }, { number: "02", title: "建立假设", text: "写下判断条件、适用边界和反例。", to: decision?.canonicalPath ?? "/library" }, { number: "03", title: "运行验证", text: "把方案放进可验证的工程流程。", to: guide?.canonicalPath ?? "/library" }, { number: "04", title: "沉淀实践", text: "把一次经验变成可复查的公开方法。", to: "/learn" }]; return <><section className="proof-hero"><p className="route-start">START</p><div className="hero-copy"><h1>每个结论，<br />都要留下证据路径</h1><p className="mono">ENGINEERING IS THE PROOF.</p><div className="hero-actions"><Link to="/cases/p007-seven-role-case">查看 P007 旗舰案例 <ArrowRight /></Link><Link to="/learn">从工程问题开始 <ArrowRight /></Link></div><p className="annotation">从问题出发，让每一步都有据可查。<br />让知识真正可复用。</p></div><aside className="boundary-note"><strong>资料边界</strong><p>✓ 公开阅读<br />✓ 来源可追溯<br />✓ 无实时问答</p><span>ENGINEERING<br />IS THE PROOF</span></aside></section><section className="proof-route"><svg className="route-line" viewBox="0 0 1200 720" preserveAspectRatio="none" aria-hidden="true"><path className="desktop-route" d="M30 0V200H1020Q1060 200 1060 240V450H760Q720 450 720 490V680H1170" /><path className="tablet-route" d="M30 0V180H1020Q1060 180 1060 220V600H760Q720 600 720 640V700H1170" /></svg><ol>{stages.map((stage, index) => <li className={`stage stage-${index + 1}`} key={stage.number}><span>{stage.number}</span><h2>{stage.title}</h2><p>{stage.text}</p><small>Source · KB-{stage.number} / v2.0</small><Link to={stage.to}>查看记录 <ArrowRight /></Link></li>)}</ol>{caseStudy && <CaseWindow item={caseStudy} />}</section><Directory items={items} title="证据目录" compact /><footer><span>GO ON</span><p>证据路径让知识可被信任，工程实践让知识创造价值。</p></footer></>; }
function CaseWindow({ item }: { item: KnowledgeItem }) { const evidence = item.evidence.find((entry) => entry.id === "p007-role-map"); return <section className="case-window"><div><p className="eyebrow red">旗舰案例</p><h2>P007 七角色编队</h2><p>{item.summary}</p><Link to={item.canonicalPath}>进入案例 <ArrowRight /></Link></div><div className="role-map"><p>七角色协作拓扑</p><b>总指挥</b><span>Product / Concept / Design / Frontend / QA</span><small>Backend 本次跳过：纯静态站</small></div><div className="case-proof"><p>公开证据 / 协作结构</p>{evidence ? <><strong>{evidence.label}</strong><a href={publicEvidenceHref(evidence.path)} target="_blank" rel="noreferrer">查看协作图 <ArrowRight /></a><small>{evidence.supports}</small></> : <><AlertTriangle /><strong>公开证据待补</strong><small>不展示未被公开证据直接支持的结论。</small></>}</div></section>; }

function Directory({ items, title, compact = false }: { items: KnowledgeItem[]; title: string; compact?: boolean }) { const [type, setType] = useState<ContentType | "all">("all"); const visible = items.filter((item) => type === "all" || item.contentType === type); return <section className={compact ? "directory compact" : "directory"}><div className="directory-head"><div><p className="eyebrow">INDEX / {items.length}</p><h1>{title}</h1></div><div className="filters" aria-label="按内容类型筛选">{typeOptions.filter((option) => option !== "case-study").map((option) => <button className={type === option ? "selected" : ""} key={option} onClick={() => setType(option)}>{option === "all" ? "全部" : typeMeta[option]}</button>)}</div></div><div aria-live="polite">{visible.length ? visible.map((item) => <ItemRow item={item} key={item.slug} />) : <section className="empty"><p>没有这类已发布内容。</p><button onClick={() => setType("all")}>清除筛选</button><Link to="/learn">查看学习路线</Link></section>}</div></section>; }
function ItemRow({ item }: { item: KnowledgeItem }) { return <Link className="item-row" to={item.canonicalPath}><span className="item-order">{String(item.order).padStart(2, "0")}</span><div><small>{typeMeta[item.contentType]} · {moduleMeta[item.module].name} · {item.contentType === "decision-card" ? `复核 ${item.reviewedAt}` : `更新 ${item.updatedAt}`}</small><h2>{item.title}</h2><p>{item.summary}</p></div><ArrowRight /></Link>; }
function Library({ items }: { items: KnowledgeItem[] }) { const [type, setType] = useState<ContentType | "all">("all"); const [module, setModule] = useState<KnowledgeItem["module"] | "all">("all"); const tags = [...new Set(items.flatMap((item) => item.tags))].sort(); const [tag, setTag] = useState("all"); const visible = items.filter((item) => (type === "all" || item.contentType === type) && (module === "all" || item.module === module) && (tag === "all" || item.tags.includes(tag))); return <section className="library"><p className="eyebrow">DISCOVERY / 27 RECORDS</p><h1>问题索引</h1><p>按真实的内容类型、主题和标签进入已发布资料。</p><div className="filter-line"><label>类型<select value={type} onChange={(event) => setType(event.target.value as ContentType | "all")}>{typeOptions.map((option) => <option key={option} value={option}>{option === "all" ? "全部" : typeMeta[option]}</option>)}</select></label><label>主题<select value={module} onChange={(event) => setModule(event.target.value as KnowledgeItem["module"] | "all")}><option value="all">全部主题</option>{moduleIds.map((id) => <option value={id} key={id}>{moduleMeta[id].name}</option>)}</select></label><label>标签<select value={tag} onChange={(event) => setTag(event.target.value)}><option value="all">全部标签</option>{tags.map((value) => <option key={value}>{value}</option>)}</select></label></div><div aria-live="polite">{visible.length ? visible.map((item) => <ItemRow item={item} key={item.slug} />) : <section className="empty"><h2>没有这类已发布内容</h2><button onClick={() => { setType("all"); setModule("all"); setTag("all"); }}>清除筛选</button><Link to="/learn">查看学习路线</Link></section>}</div></section>; }
function Learn({ items }: { items: KnowledgeItem[] }) { return <section className="learn"><p className="eyebrow">OPTIONAL / LEARNING ROUTE</p><h1>可选学习路线</h1><p>路线只提供开始点；你可以从任何记录跳入、跳过或回到检索。</p><ol>{items.map((item) => <li key={item.slug}><ItemRow item={item} /></li>)}</ol></section>; }
function SearchPage({ items }: { items: KnowledgeItem[] }) { const navigate = useNavigate(); const location = useLocation(); const initial = new URLSearchParams(location.search).get("q") ?? ""; const [query, setQuery] = useState(initial); const input = useRef<HTMLInputElement>(null); const normalized = query.trim(); const results = useMemo(() => normalized.length === 1 ? [] : searchItems(items, normalized), [items, normalized]); useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "/" && !(event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement)) { event.preventDefault(); input.current?.focus(); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []); useEffect(() => { const timer = window.setTimeout(() => navigate(normalized ? `/search?q=${encodeURIComponent(normalized)}` : "/search", { replace: true }), 180); return () => window.clearTimeout(timer); }, [navigate, normalized]); return <section className="search-page"><p className="eyebrow">SEARCH / EVIDENCE LINE</p><h1>搜索记录</h1><form className="search-line" onSubmit={(event) => { event.preventDefault(); input.current?.focus(); }}><Search /><input ref={input} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="输入概念、术语或工程问题" aria-label="搜索知识库" />{query && <button type="button" onClick={() => setQuery("")}>清空</button>}</form><p className="mono">按 / 聚焦搜索</p>{normalized.length === 1 ? <section className="empty"><p>再输入一个字符以获得稳定结果。</p></section> : results.length ? <div aria-live="polite"><p className="result-note">{normalized ? `找到 ${results.length} 项匹配记录` : "浏览全部已发布记录"}</p>{results.map((hit) => <Link className="item-row" to={hit.item.canonicalPath} key={hit.item.slug}><span className="item-order">{String(hit.item.order).padStart(2, "0")}</span><div><small>{hit.fields.length ? `命中：${hit.fields.join(" / ")}` : typeMeta[hit.item.contentType]}</small><h2>{hit.item.title}</h2><p>{hit.excerpt}</p></div><ArrowRight /></Link>)}</div> : <section className="empty"><h2>没有找到“{normalized}”</h2><p>换一个术语，或从学习路线继续探索。</p><Link to="/learn">查看学习路线</Link></section>}</section>; }
function Detail({ items }: { items: KnowledgeItem[] }) { const { slug } = useParams(); const item = items.find((entry) => entry.slug === slug); if (!item) return <NotFound />; const related = item.related.map((target) => items.find((entry) => entry.slug === target)).filter(Boolean) as KnowledgeItem[]; const sourceAt = item.body.search(/^##\s+原始来源\s*$/m); const body = sourceAt >= 0 ? item.body.slice(0, sourceAt) : item.body; return <article className="detail"><Link className="back" to="/library">← 返回问题索引</Link><p className="eyebrow">{typeMeta[item.contentType]} / {moduleMeta[item.module].name} / 更新 {item.updatedAt}</p>{item.contentType === "decision-card" && <div className={item.reviewStatus === "review-needed" ? "review needed" : "review current"}>{item.reviewStatus === "review-needed" ? <AlertTriangle /> : <Clock3 />}<strong>{item.reviewStatus === "review-needed" ? "待复核：历史判断，需自行复核" : "当前：已完成来源复核"}</strong><span>复核日期 {item.reviewedAt}</span></div>}<h1>{item.title}</h1><p className="lede">{item.summary}</p><div className="metadata"><span>前置：{item.prerequisites.length ? item.prerequisites.join("、") : "无"}</span><span>约 {Math.max(1, Math.ceil(item.body.length / 420))} 分钟</span>{item.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div>{item.contentType === "decision-card" && <div className="table-scroll"><p>比较矩阵：左右滑动查看全部条件。</p><table><caption>{item.title}的选择条件</caption><tbody><tr><th>比较对象</th><td>{item.tags.join(" / ")}</td></tr><tr><th>判断条件</th><td>{item.summary}</td></tr><tr><th>人工门禁</th><td>{item.reviewStatus === "review-needed" ? "待复核内容不可直接作为当前推荐。" : "高影响结论保留人工复核。"}</td></tr><tr><th>回退策略</th><td>证据、权限或评估不足时，回到更窄能力边界或人工处理。</td></tr></tbody></table></div>}<Markdown body={body} headings={item.headings} /><section className="sources"><h2>来源与公开证据</h2>{item.evidence.map((evidence) => <a href={publicEvidenceHref(evidence.path)} key={evidence.id} target="_blank" rel="noreferrer">{evidence.label}<small>{evidence.supports}</small></a>)}{item.sources.map((source) => <a href={source.url} key={source.id} target="_blank" rel="noreferrer">{source.title}<small>外部资料 / 新标签页 <ExternalLink /></small></a>)}</section><section className="related"><h2>继续探索</h2>{related.map((entry) => <Link key={entry.slug} to={entry.canonicalPath}>{entry.title} <ArrowRight /></Link>)}<Link to="/learn">进入学习路线 <ArrowRight /></Link></section></article>; }
export function Markdown({ body, headings }: { body: string; headings: KnowledgeItem["headings"] }) { const sourceBoundary = body.search(/^##\s+原始来源\s*$/m); const safeBody = sourceBoundary >= 0 ? body.slice(0, sourceBoundary) : body; const anchors = new Map(headings.map((heading) => [heading.text, heading.anchor])); return <div className="markdown"><ReactMarkdown skipHtml components={{ a: ({ href, children }) => <a href={href ? publicEvidenceHref(href) : href}>{children}</a>, h2: ({ children }) => <h2 id={anchors.get(String(children))}>{children}</h2>, h3: ({ children }) => <h3 id={anchors.get(String(children))}>{children}</h3> }}>{safeBody}</ReactMarkdown></div>; }
function NotFound() { return <section className="state"><p className="eyebrow">RECORD / 404</p><h1>未找到这份记录</h1><p>地址可能不存在，或内容尚未发布。</p><div className="actions"><Link to="/">返回首页</Link><Link to="/learn">学习路线</Link><Link to="/search">搜索</Link></div></section>; }
export default App;
