import { describe, expect, it } from "vitest";
import { isKnowledgeIndex, searchItems } from "./knowledge";
import type { KnowledgeIndex, KnowledgeItem } from "./types";

const item = (order: number, title: string, summary: string, tags: string[], headings: string[], body: string): KnowledgeItem => ({ slug: `item-${order}`, title, contentType: "note", module: "ai-foundations", order, summary, tags, updatedAt: "2026-08-15", reviewedAt: null, reviewStatus: null, prerequisites: [], related: ["item-1"], sources: [], evidence: [], headings: headings.map((text) => ({ level: 2, text, anchor: text })), body, contentHash: "a", canonicalPath: `/notes/item-${order}` });

describe("weighted Chinese search", () => { it("sorts contract fields by specified weight", () => { const results = searchItems([item(1, "检索词标题", "", [], [], ""), item(2, "普通", "检索词摘要", [], [], ""), item(3, "普通", "", ["检索词标签"], [], ""), item(4, "普通", "", [], ["检索词小标题"], ""), item(5, "普通", "", [], [], "检索词正文")], "检索词"); expect(results.map((entry) => entry.item.order)).toEqual([1, 2, 3, 4, 5]); }); });

describe("V2 runtime index validator", () => { const valid = (): KnowledgeIndex => { const entries = Array.from({ length: 27 }, (_, index) => ({ ...item(index + 1, "标题", "摘要", ["标签"], ["小标题"], "正文"), contentType: index < 12 ? "note" : index < 22 ? "guide" : index < 26 ? "decision-card" : "case-study" } as KnowledgeItem)); entries.forEach((entry) => { entry.canonicalPath = entry.contentType === "note" ? `/notes/${entry.slug}` : entry.contentType === "guide" ? `/guides/${entry.slug}` : entry.contentType === "decision-card" ? `/decisions/${entry.slug}` : `/cases/${entry.slug}`; if (entry.contentType === "decision-card") { entry.reviewedAt = "2026-08-15"; entry.reviewStatus = "current"; } }); return { schemaVersion: 2, generatedAt: "2026-08-15T00:00:00.000Z", items: entries, counts: { total: 27, note: 12, guide: 10, decisionCard: 4, caseStudy: 1 } }; }; it("accepts real distribution and rejects schema, counts, type and review regressions", () => { expect(isKnowledgeIndex(valid())).toBe(true); expect(isKnowledgeIndex({ ...valid(), schemaVersion: 1 })).toBe(false); expect(isKnowledgeIndex({ ...valid(), counts: { ...valid().counts, guide: 9 } })).toBe(false); const wrongType = valid(); wrongType.items[1] = { ...wrongType.items[1], contentType: "unknown" as "note" }; expect(isKnowledgeIndex(wrongType)).toBe(false); const wrongReview = valid(); wrongReview.items[22] = { ...wrongReview.items[22], reviewedAt: null }; expect(isKnowledgeIndex(wrongReview)).toBe(false); const falseDistribution = valid(); falseDistribution.items[12] = { ...falseDistribution.items[12], contentType: "note", canonicalPath: "/notes/item-13" }; expect(isKnowledgeIndex(falseDistribution)).toBe(false); }); });
