<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { useMallStore } from '../../stores/mall'
import OrderStatus from '../../components/OrderStatus.vue'
const store = useMallStore(); const id=ref(''); onLoad((query)=>{id.value=String(query?.id||'')}); const order=computed(()=>store.database.orders.find((item)=>item.id===id.value))
const cancel=async()=>{try{await store.cancel(id.value);uni.showToast({title:'订单已取消',icon:'success'})}catch(error){uni.showToast({title:(error as Error).message,icon:'none'})}}
const goPayment = () => { if (order.value) uni.redirectTo({ url: `/pages/payment/index?id=${order.value.id}` }) }
const goAfterSale = () => { if (order.value) uni.navigateTo({ url: `/pages/aftersale/index?id=${order.value.id}` }) }
</script>
<template><view class="page" v-if="order"><view class="state"><view><text class="eyebrow">ORDER STATUS</text><view class="serif">{{order.status==='pending_payment'?'等待你的决定':'栖物正在准备'}}</view></view><OrderStatus :status="order.status"/></view><view class="panel"><view class="row"><text class="serif">收货信息</text><text class="muted">{{order.address.name}} {{order.address.phone}}</text></view><view class="muted address">{{order.address.region}} {{order.address.detail}}</view></view><view class="panel"><view v-for="line in order.lines" :key="line.sku.id" class="line"><image :src="line.product.image" mode="aspectFill"/><view><view class="serif">{{line.product.name}}</view><text class="muted">{{line.sku.name}} × {{line.quantity}}</text></view><text>¥{{line.lineTotal}}</text></view></view><view class="panel totals"><view class="row"><text>商品小计</text><text>¥{{order.goodsTotal}}</text></view><view class="row"><text>运费</text><text>¥{{order.shipping}}</text></view><view class="row"><text>优惠</text><text>-¥{{order.discount}}</text></view><view class="row strong"><text>实付款</text><text>¥{{order.total}}</text></view></view><view v-if="order.status==='pending_payment'" class="primary" @click="goPayment">去模拟支付</view><view v-if="order.status==='pending_payment'" class="secondary" @click="cancel">取消订单</view><view v-if="order.status==='completed'" class="primary" @click="goAfterSale">申请售后</view><view v-if="order.status==='after_sale'" class="notice">已提交售后申请：{{order.afterSale?.reason}}</view></view></template>
<style scoped lang="scss">.state{background:#173b2a;color:#fffdf8;margin:-28rpx -28rpx 28rpx;padding:52rpx 28rpx;display:flex;justify-content:space-between;align-items:flex-end}.state .serif{font-size:42rpx;margin-top:13rpx}.line{display:grid;grid-template-columns:100rpx 1fr auto;gap:16rpx;align-items:center;margin:15rpx 0}.line image{width:100rpx;height:100rpx;border-radius:10rpx}.line .serif{font-size:27rpx;color:#173b2a}.address{margin-top:15rpx}.totals .row{padding:10rpx 0;font-size:25rpx}.strong{color:#c96842;font-weight:700}.secondary{margin-top:20rpx}</style>
