<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { products } from '../../data/seed'
import { useMallStore } from '../../stores/mall'
const store = useMallStore(); const productId = ref('cup'); const selectedSkuId = ref(''); const quantity = ref(1)
onLoad((query) => { productId.value = String(query?.id || 'cup'); selectedSkuId.value = product.value.skus[0]?.id ?? '' })
const product = computed(() => products.find((item) => item.id === productId.value) ?? products[0]); const sku = computed(() => product.value.skus.find((item) => item.id === selectedSkuId.value) ?? product.value.skus[0])
const add = async (checkout = false) => { try { await store.addToCart(product.value.id, sku.value.id, quantity.value); uni.showToast({title:'已加入购物袋',icon:'success'}); if (checkout) { store.prepareCheckout(); uni.navigateTo({url:'/pages/checkout/index'}) } } catch (error) { uni.showToast({title:(error as Error).message,icon:'none'}) } }
</script>
<template><view class="page product"><image class="cover" :src="product.image" mode="aspectFill"/><view class="tags"><text v-for="tag in product.tags" :key="tag">{{tag}}</text></view><view class="serif name">{{ product.name }}</view><view class="sub">{{product.subtitle}}</view><view class="price">¥{{ sku.price }}</view><view class="panel"><text class="label">选择规格</text><view class="sku-list"><text v-for="item in product.skus" :key="item.id" :class="{chosen:selectedSkuId===item.id}" @click="selectedSkuId=item.id">{{item.name}} · {{item.specs}}</text></view><view class="row"><text class="label">数量</text><view class="step"><text @click="quantity=Math.max(1,quantity-1)">−</text><text>{{quantity}}</text><text @click="quantity=Math.min(sku.stock,quantity+1)">＋</text></view></view><view class="stock">库存 {{sku.stock}} 件</view></view><view class="bottom"><text class="secondary" @click="add(false)">加入购物袋</text><text class="primary" @click="add(true)">立即购买</text></view></view></template>
<style scoped lang="scss">.product{padding:0 0 150rpx}.cover{width:100%;height:750rpx;background:#ddd4c2}.product>.tags,.name,.sub,.price,.panel{margin-left:28rpx;margin-right:28rpx}.tags{display:flex;gap:10rpx;margin-top:24rpx}.tags text{background:#e5e7dc;color:#71836a;border-radius:999rpx;padding:7rpx 13rpx;font-size:21rpx}.name{font-size:50rpx;color:#173b2a;margin-top:20rpx}.sub{font-size:25rpx;color:#71836a;margin-top:11rpx}.price{margin-top:28rpx}.label{font-size:25rpx;color:#173b2a}.sku-list{display:flex;gap:14rpx;flex-wrap:wrap;margin:18rpx 0 28rpx}.sku-list text{padding:15rpx;font-size:24rpx;border:1rpx solid #d8d4c7;border-radius:12rpx}.sku-list .chosen{border-color:#173b2a;background:#e8eadf}.step{display:flex;gap:28rpx;align-items:center;border:1rpx solid #d8d4c7;padding:10rpx 14rpx;border-radius:999rpx}.stock{font-size:22rpx;color:#71836a;margin-top:19rpx}.bottom{position:fixed;bottom:0;left:0;right:0;z-index:3;background:#fffdf8;padding:20rpx 28rpx calc(20rpx + env(safe-area-inset-bottom));display:grid;grid-template-columns:1fr 1.2fr;gap:18rpx}.bottom text{box-sizing:border-box}</style>
