<script setup lang="ts">
import { computed } from 'vue'
import { useMallStore } from '../../stores/mall'
const store = useMallStore(); store.hydrate(); const total = computed(() => store.cartDetails.filter((item)=>item.selected).reduce((sum,item)=>sum+item.subtotal,0))
const change = async (id:string, next:number) => { try { await store.updateLine(id,next) } catch(error) { uni.showToast({title:(error as Error).message,icon:'none'}) } }
const checkout = () => { try { store.prepareCheckout(); uni.navigateTo({url:'/pages/checkout/index'}) } catch(error) { uni.showToast({title:(error as Error).message,icon:'none'}) } }
const toggle = (id: string, event: Event) => store.setSelected(id, (event as unknown as { detail: { value: boolean } }).detail.value)
const goCatalog = () => uni.switchTab({ url: '/pages/catalog/index' })
</script>
<template><view class="page"><text class="eyebrow">YOUR QIWU BAG</text><view class="section-title">购物袋</view><view v-if="store.cartDetails.length"><view v-for="line in store.cartDetails" :key="line.id" class="line panel"><switch :checked="line.selected" color="#173B2A" @change="toggle(line.id,$event)"/><image :src="line.product.image" mode="aspectFill"/><view class="info"><view class="serif">{{line.product.name}}</view><view class="muted">{{line.sku.name}} · {{line.sku.specs}}</view><view class="row"><view class="step"><text @click="change(line.id,line.quantity-1)">−</text><text>{{line.quantity}}</text><text @click="change(line.id,line.quantity+1)">＋</text></view><text class="price">¥{{line.subtotal}}</text></view></view><text class="remove" @click="store.removeLine(line.id)">移除</text></view></view><view v-else class="empty"><view class="serif">还没有选物</view><text @click="goCatalog">去看看今日选物 →</text></view><view v-if="store.cartDetails.length" class="checkout"><view><text class="muted">合计（不含运费）</text><view class="price">¥{{total}}</view></view><text class="primary" @click="checkout">去结算</text></view></view></template>
<style scoped lang="scss">.line{display:grid;grid-template-columns:45rpx 140rpx 1fr 45rpx;gap:18rpx;align-items:center}.line image{width:140rpx;height:140rpx;border-radius:12rpx}.info{min-width:0}.info .serif{font-size:29rpx;color:#173b2a}.info .muted{margin:10rpx 0}.step{display:flex;gap:18rpx;align-items:center;color:#173b2a;font-size:27rpx}.remove{font-size:21rpx;color:#71836a;text-align:right}.empty{text-align:center;padding:180rpx 0;color:#71836a}.empty .serif{font-size:42rpx;color:#173b2a;margin-bottom:22rpx}.checkout{position:fixed;bottom:100rpx;left:0;right:0;background:#fffdf8;padding:20rpx 28rpx calc(20rpx + env(safe-area-inset-bottom));display:flex;align-items:center;justify-content:space-between}.checkout .primary{width:220rpx;padding:20rpx}</style>
