<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useMallStore } from '../../stores/mall'
const store = useMallStore(); onMounted(() => { if (!store.checkoutLineIds.length) { try { store.prepareCheckout() } catch { uni.navigateBack() } } })
const quote = computed(() => store.quote)
const chooseAddress = () => uni.navigateTo({url:'/pages/address/index?pick=1'})
const chooseCoupon = () => uni.navigateTo({url:'/pages/coupon/index'})
const submit = async () => { try { const order = await store.createOrder(); uni.navigateTo({url:`/pages/payment/index?id=${order.id}`}) } catch(error) { uni.showToast({title:(error as Error).message,icon:'none'}) } }
</script>
<template><view class="page" v-if="quote"><text class="eyebrow">CHECKOUT / DEMO</text><view class="section-title">确认订单</view><view class="panel" @click="chooseAddress"><view class="row"><text class="serif">收货地址</text><text>›</text></view><view v-if="store.defaultAddress" class="address"><b>{{store.defaultAddress.name}} {{store.defaultAddress.phone}}</b><text>{{store.defaultAddress.region}} {{store.defaultAddress.detail}}</text></view><view v-else class="muted">请选择收货地址</view></view><view class="panel"><view v-for="line in quote.lines" :key="line.sku.id" class="item"><image :src="line.product.image" mode="aspectFill"/><view><view class="serif">{{line.product.name}}</view><view class="muted">{{line.sku.name}} × {{line.quantity}}</view></view><text>¥{{line.lineTotal}}</text></view></view><view class="panel" @click="chooseCoupon"><view class="row"><text>优惠券</text><text>{{quote.coupon ? `-${quote.discount}` : '选择优惠券'}} ›</text></view></view><view class="panel totals"><view class="row"><text>商品小计</text><text>¥{{quote.goodsTotal}}</text></view><view class="row"><text>运费</text><text>{{quote.shipping ? `¥${quote.shipping}` : '免运费'}}</text></view><view class="row" v-if="quote.discount"><text>优惠</text><text>-¥{{quote.discount}}</text></view></view><view class="notice">本订单只用于功能演示，不会产生真实交易或物流。</view><view class="bottom"><view><text class="muted">实付款</text><text class="price"> ¥{{quote.total}}</text></view><text class="primary" @click="submit">提交模拟订单</text></view></view></template>
<style scoped lang="scss">.address{display:flex;flex-direction:column;gap:11rpx;font-size:25rpx;line-height:1.6;margin-top:18rpx}.item{display:grid;grid-template-columns:100rpx 1fr auto;gap:16rpx;align-items:center;padding:10rpx 0}.item image{width:100rpx;height:100rpx;border-radius:10rpx}.item .serif{font-size:27rpx;color:#173b2a}.totals .row{padding:12rpx 0;font-size:26rpx}.bottom{position:fixed;bottom:0;left:0;right:0;background:#fffdf8;padding:20rpx 28rpx calc(20rpx + env(safe-area-inset-bottom));display:flex;justify-content:space-between;align-items:center}.bottom .primary{width:280rpx;padding:20rpx}</style>
