<script setup lang="ts">
import { computed, ref } from 'vue'
import { useMallStore } from '../../stores/mall'
import OrderStatus from '../../components/OrderStatus.vue'
const store = useMallStore(); const filter = ref('all'); const labels = [{id:'all',name:'全部'},{id:'pending_payment',name:'待付款'},{id:'pending_shipment',name:'待发货'},{id:'in_transit',name:'运输中'},{id:'completed',name:'已完成'}]
const orders = computed(()=>store.database.orders.filter((item)=>filter.value==='all'||item.status===filter.value))
const detail=(id:string)=>uni.navigateTo({url:`/pages/order/index?id=${id}`})
</script>
<template><view class="page"><text class="eyebrow">YOUR QIWU ORDERS</text><view class="section-title">我的订单</view><scroll-view scroll-x class="filters"><text v-for="item in labels" :key="item.id" :class="{active:filter===item.id}" @click="filter=item.id">{{item.name}}</text></scroll-view><view v-for="order in orders" :key="order.id" class="panel order" @click="detail(order.id)"><view class="row"><text class="muted">{{order.number}}</text><OrderStatus :status="order.status"/></view><view v-for="line in order.lines.slice(0,1)" :key="line.sku.id" class="line"><image :src="line.product.image" mode="aspectFill"/><view><view class="serif">{{line.product.name}}</view><text class="muted">{{line.sku.name}} × {{line.quantity}}</text></view><text>¥{{line.lineTotal}}</text></view><view class="row total"><text>共 {{order.lines.length}} 件</text><text>实付 <b>¥{{order.total}}</b></text></view></view><view v-if="!orders.length" class="empty">暂无对应订单</view></view></template>
<style scoped lang="scss">.filters{white-space:nowrap;margin:0 -28rpx 26rpx;width:calc(100% + 56rpx)}.filters text{display:inline-block;margin-left:28rpx;font-size:25rpx;color:#71836a;padding:12rpx 18rpx}.filters .active{background:#173b2a;color:white;border-radius:999rpx}.line{display:grid;grid-template-columns:110rpx 1fr auto;gap:18rpx;align-items:center;margin:20rpx 0}.line image{width:110rpx;height:110rpx;border-radius:10rpx}.line .serif{font-size:28rpx;color:#173b2a}.total{border-top:1rpx solid #e8e4d9;padding-top:18rpx;font-size:24rpx}.empty{text-align:center;padding:160rpx 0;color:#71836a}</style>
